/*
 * agent-flow-studio — scripts/analyze-flows.js
 * -----------------------------------------------------------------------------
 * A tiny, dependency-free CLI around analysis.js — the sibling of lint-flows.js.
 * It runs the data-dependency / provenance analyzer over every flow in examples/
 * (the "good" reference flows) and test/fixtures/ (labelled valid / invalid
 * samples), prints a summary table to the terminal, and writes a deterministic
 * Markdown report to docs/FLOW_DEPENDENCY_REPORT.md.
 *
 * Determinism: the report contains NO timestamps or machine-specific paths, so
 * re-running it produces the file byte-for-byte. Files are visited in sorted
 * order and every list the analyzer emits is already sorted.
 *
 * Usage:
 *     node scripts/analyze-flows.js            # analyze + print summary
 *     node scripts/analyze-flows.js --write    # also (re)write the Markdown report
 *     node scripts/analyze-flows.js --check    # fail (exit 1) if the report is stale
 *
 * Exit code is 0 on success. `--check` exits 1 when the on-disk report differs
 * from the freshly generated one (useful in CI). This is a report generator over
 * sample flows, some of which are deliberately invalid — findings never set the
 * exit code.
 *
 * Author: Dimitres Kisimov. © 2026 — all rights reserved (portfolio review only; see LICENSE).
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const analysis = require('../analysis.js');

const ROOT = path.join(__dirname, '..');
const REPORT_PATH = path.join(ROOT, 'docs', 'FLOW_DEPENDENCY_REPORT.md');

const SOURCES = [
  { dir: path.join(ROOT, 'examples'), heading: 'Shipped example flows', note: 'The two flows the app ships in `examples/`. These are valid DAGs.' },
  { dir: path.join(ROOT, 'test', 'fixtures'), heading: 'Analyzer fixtures', note: 'Illustrative samples reused from the test suite — some are deliberately broken (a cycle, a self-loop, an orphaned subgraph) to show how the analysis degrades honestly. Names starting with `invalid-` are broken on purpose.' }
];

function listFlows(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((f) => f.endsWith('.json')).sort();
}

function analyzeOne(dir, file) {
  const raw = fs.readFileSync(path.join(dir, file), 'utf8');
  let flow;
  try {
    flow = JSON.parse(raw);
  } catch (err) {
    return { file: file, name: '(unparseable)', result: null, parseError: err.message };
  }
  return { file: file, name: typeof flow.name === 'string' ? flow.name : '(unnamed)', result: analysis.analyzeFlow(flow) };
}

function collect() {
  return SOURCES.map((src) => ({
    heading: src.heading,
    note: src.note,
    rel: path.relative(ROOT, src.dir).replace(/\\/g, '/'),
    entries: listFlows(src.dir).map((f) => analyzeOne(src.dir, f))
  }));
}

/* --- Markdown report (deterministic) ----------------------------------- */
function buildReport(groups) {
  const L = [];
  L.push('# Flow dependency report');
  L.push('');
  L.push('Generated by `node scripts/analyze-flows.js --write` from the flows in the folders below.');
  L.push('It is a pure, deterministic function of those files — re-running reproduces it byte-for-byte,');
  L.push('so it can be committed and diffed. The example flows are illustrative, not exhaustive.');
  L.push('');
  L.push('This is a **static** data-dependency analysis over the graph edges and node types alone. It');
  L.push('reports each node\'s dependencies, the topological run order, the **stages** whose nodes could');
  L.push('run in parallel, the **critical path** (the minimum number of sequential stages), and the');
  L.push('**provenance** of every Output (which Trigger can feed it). Like the linter it treats BOTH');
  L.push('branches of a Condition as reachable — it does not follow the single branch taken at run time,');
  L.push('so these describe *potential* data flow, not the one path a given input takes.');
  L.push('');

  for (const g of groups) {
    L.push('## ' + g.heading);
    L.push('');
    L.push('_' + g.note + '_ (`' + g.rel + '/`)');
    L.push('');
    L.push('| Flow | File | Nodes | Edges | DAG? | Stages | Depth |');
    L.push('| --- | --- | ---: | ---: | --- | ---: | ---: |');
    for (const e of g.entries) {
      if (!e.result) {
        L.push('| ' + mdCell(e.name) + ' | `' + e.file + '` | — | — | — | — | — |');
        continue;
      }
      const r = e.result;
      const dag = r.acyclic ? 'yes' : 'no (cycle)';
      const stages = r.acyclic ? String(r.stages.length) : '—';
      const depth = r.acyclic ? String(r.depth) : '—';
      L.push('| ' + mdCell(e.name) + ' | `' + e.file + '` | ' + r.nodeCount + ' | ' + r.edgeCount + ' | ' + dag + ' | ' + stages + ' | ' + depth + ' |');
    }
    L.push('');

    for (const e of g.entries) {
      if (!e.result) {
        L.push('### `' + e.file + '` — not valid JSON');
        L.push('');
        L.push('- ' + mdCell(e.parseError));
        L.push('');
        continue;
      }
      const r = e.result;
      L.push('### `' + e.file + '` — ' + mdCell(analysis.summarize(r)));
      L.push('');
      if (r.nodeCount === 0) {
        L.push('- empty flow — nothing to analyze');
        L.push('');
        continue;
      }
      if (r.acyclic) {
        L.push('- **Run order:** ' + r.order.map(code).join(' -> '));
        L.push('- **Stages (each stage could run in parallel):**');
        r.stages.forEach((s, i) => {
          L.push('  - stage ' + i + ': ' + s.map(code).join(', '));
        });
        L.push('- **Critical path (' + r.depth + ' deep):** ' + r.criticalPath.map(code).join(' -> '));
      } else {
        L.push('- **Not a DAG** — cycle involving ' + r.cycleNodes.map(code).join(', ') + '; run order, stages and critical path are withheld.');
      }
      // Provenance: which trigger(s) feed each output.
      if (r.outputs.length) {
        L.push('- **Provenance (output ← trigger):**');
        r.outputs.forEach((o) => {
          const from = r.provenance.byOutput[o];
          L.push('  - ' + code(o) + ' ← ' + (from.length ? from.map(code).join(', ') : '_no trigger — this output is unreachable_'));
        });
      }
      L.push('');
    }
  }

  L.push('## What each column means');
  L.push('');
  L.push('| Field | Meaning |');
  L.push('| --- | --- |');
  L.push('| Nodes / Edges | Node count and raw edge count of the flow. |');
  L.push('| DAG? | Whether the dependency graph is acyclic. A cycle or self-loop makes it `no`. |');
  L.push('| Stages | Number of topological levels. Nodes in one stage have no dependency between them, so they could run in parallel. |');
  L.push('| Depth | Length of the critical path — the minimum number of sequential stages the flow needs. |');
  L.push('| Provenance | For each Output, the Trigger(s) whose payload can reach it (both Condition branches counted). |');
  L.push('');
  return L.join('\n') + '\n';
}

function code(s) { return '`' + s + '`'; }
function mdCell(s) { return String(s == null ? '' : s).replace(/\|/g, '\\|'); }

/* --- Terminal summary --------------------------------------------------- */
function printSummary(groups) {
  let flows = 0;
  let cyclic = 0;
  for (const g of groups) {
    process.stdout.write('\n' + g.heading + ' (' + g.rel + '/)\n');
    for (const e of g.entries) {
      flows += 1;
      if (!e.result) {
        process.stdout.write('  FAIL  ' + e.file + '  (not valid JSON)\n');
        continue;
      }
      if (!e.result.acyclic) cyclic += 1;
      const tag = e.result.acyclic ? 'ok   ' : 'CYCLE';
      process.stdout.write('  ' + tag + '  ' + e.file + '  (' + analysis.summarize(e.result) + ')\n');
    }
  }
  process.stdout.write('\n' + flows + ' flow(s): ' + cyclic + ' with a cycle.\n');
}

/* --- Main --------------------------------------------------------------- */
function main() {
  const args = process.argv.slice(2);
  const write = args.includes('--write');
  const check = args.includes('--check');

  const groups = collect();
  printSummary(groups);

  const report = buildReport(groups);

  if (check) {
    const current = fs.existsSync(REPORT_PATH) ? fs.readFileSync(REPORT_PATH, 'utf8') : '';
    if (current !== report) {
      process.stderr.write('\nFLOW_DEPENDENCY_REPORT.md is out of date. Run: node scripts/analyze-flows.js --write\n');
      process.exit(1);
    }
    process.stdout.write('\nReport is up to date.\n');
    return;
  }

  if (write) {
    fs.writeFileSync(REPORT_PATH, report);
    process.stdout.write('\nWrote ' + path.relative(ROOT, REPORT_PATH).replace(/\\/g, '/') + '\n');
  }
}

main();
