/*
 * agent-flow-studio — scripts/lint-flows.js
 * -----------------------------------------------------------------------------
 * A tiny, dependency-free CLI around linter.js. It lints every flow in
 * examples/ (the "good" reference flows) and test/fixtures/ (labelled valid /
 * invalid samples), prints a summary table to the terminal, and writes a
 * deterministic Markdown report to docs/FLOW_LINT_REPORT.md.
 *
 * Determinism: the report contains NO timestamps or machine-specific paths, so
 * re-running it produces the file byte-for-byte. Files are visited in sorted
 * order and diagnostics are already sorted by the linter.
 *
 * Usage:
 *     node scripts/lint-flows.js            # lint + print summary
 *     node scripts/lint-flows.js --write    # also (re)write the Markdown report
 *     node scripts/lint-flows.js --check    # fail (exit 1) if the report is stale
 *
 * Exit code is 0 on success. `--check` exits 1 when the on-disk report differs
 * from the freshly generated one (useful in CI). Lint findings do NOT set the
 * exit code — this is a report generator over sample flows, some of which are
 * deliberately invalid.
 *
 * Author: Dimitres Kisimov. © 2026 — all rights reserved (portfolio review only; see LICENSE).
 */
'use strict';

const fs = require('node:fs');
const path = require('node:path');

const linter = require('../linter.js');

const ROOT = path.join(__dirname, '..');
const REPORT_PATH = path.join(ROOT, 'docs', 'FLOW_LINT_REPORT.md');

// Sources to lint, in report order. `expect` documents the intent of each set.
const SOURCES = [
  { dir: path.join(ROOT, 'examples'), heading: 'Shipped example flows', note: 'The two flows the app ships in `examples/`. These are expected to be clean.' },
  { dir: path.join(ROOT, 'test', 'fixtures'), heading: 'Linter fixtures', note: 'Illustrative samples used by the test suite — some are deliberately invalid to exercise a rule. Names starting with `invalid-` are broken on purpose.' }
];

function listFlows(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((f) => f.endsWith('.json')).sort();
}

function lintOne(dir, file) {
  const raw = fs.readFileSync(path.join(dir, file), 'utf8');
  let flow;
  try {
    flow = JSON.parse(raw);
  } catch (err) {
    return { file: file, name: '(unparseable)', result: null, parseError: err.message };
  }
  return { file: file, name: typeof flow.name === 'string' ? flow.name : '(unnamed)', result: linter.lintFlow(flow) };
}

function collect() {
  return SOURCES.map((src) => ({
    heading: src.heading,
    note: src.note,
    rel: path.relative(ROOT, src.dir).replace(/\\/g, '/'),
    entries: listFlows(src.dir).map((f) => lintOne(src.dir, f))
  }));
}

/* --- Markdown report (deterministic) ----------------------------------- */
function buildReport(groups) {
  const L = [];
  L.push('# Flow lint report');
  L.push('');
  L.push('Generated by `node scripts/lint-flows.js --write` from the flows in the folders below.');
  L.push('It is a pure, deterministic function of those files — re-running reproduces it byte-for-byte,');
  L.push('so it can be committed and diffed. The example flows are illustrative, not exhaustive.');
  L.push('');
  L.push('The linter reports **structural / wiring** problems that are decidable from the graph and the');
  L.push('node specs alone (see the rule table at the end). It does not prove a flow is correct, reason');
  L.push('about payload contents, or follow the data-dependent branch a Condition takes at run time.');
  L.push('');

  for (const g of groups) {
    L.push('## ' + g.heading);
    L.push('');
    L.push('_' + g.note + '_ (`' + g.rel + '/`)');
    L.push('');
    L.push('| Flow | File | Errors | Warnings | Verdict |');
    L.push('| --- | --- | ---: | ---: | --- |');
    for (const e of g.entries) {
      if (!e.result) {
        L.push('| ' + mdCell(e.name) + ' | `' + e.file + '` | — | — | not valid JSON |');
        continue;
      }
      const r = e.result;
      const verdict = r.errorCount ? 'FAIL' : (r.warningCount ? 'warnings' : 'clean');
      L.push('| ' + mdCell(e.name) + ' | `' + e.file + '` | ' + r.errorCount + ' | ' + r.warningCount + ' | ' + verdict + ' |');
    }
    L.push('');

    // Per-flow detail for anything that is not clean.
    for (const e of g.entries) {
      if (!e.result) {
        L.push('### `' + e.file + '` — not valid JSON');
        L.push('');
        L.push('- ' + mdCell(e.parseError));
        L.push('');
        continue;
      }
      if (!e.result.diagnostics.length) continue;
      L.push('### `' + e.file + '` — ' + linter.summaryLine(e.result));
      L.push('');
      for (const d of e.result.diagnostics) {
        const where = d.target.kind + (d.target.id ? ' `' + d.target.id + '`' : '');
        L.push('- **' + d.severity + '** · `' + d.code + '` · ' + where + ' — ' + mdCell(d.message));
      }
      L.push('');
    }
  }

  // Rule reference table — the honest list of what the linter checks.
  L.push('## Rules');
  L.push('');
  L.push('| Code | Severity | What it means |');
  L.push('| --- | --- | --- |');
  for (const code of Object.keys(linter.RULES).sort()) {
    const rule = linter.RULES[code];
    L.push('| `' + code + '` | ' + rule.severity + ' | ' + mdCell(rule.summary) + ' |');
  }
  L.push('');
  return L.join('\n') + '\n';
}

function mdCell(s) {
  return String(s == null ? '' : s).replace(/\|/g, '\\|');
}

/* --- Terminal summary --------------------------------------------------- */
function printSummary(groups) {
  let totalErr = 0;
  let totalWarn = 0;
  let flows = 0;
  for (const g of groups) {
    process.stdout.write('\n' + g.heading + ' (' + g.rel + '/)\n');
    for (const e of g.entries) {
      flows += 1;
      if (!e.result) {
        process.stdout.write('  FAIL  ' + e.file + '  (not valid JSON)\n');
        continue;
      }
      totalErr += e.result.errorCount;
      totalWarn += e.result.warningCount;
      const tag = e.result.errorCount ? 'FAIL ' : (e.result.warningCount ? 'WARN ' : 'clean');
      process.stdout.write('  ' + tag + '  ' + e.file + '  (' + linter.summaryLine(e.result) + ')\n');
    }
  }
  process.stdout.write('\n' + flows + ' flow(s): ' + totalErr + ' error(s), ' + totalWarn + ' warning(s).\n');
}

/* --- Main --------------------------------------------------------------- */
function main() {
  const args = process.argv.slice(2);
  const write = args.includes('--write');
  const check = args.includes('--check');

  const groups = collect();
  printSummary(groups);

  const report = buildReport(groups);

  if (check) {
    const current = fs.existsSync(REPORT_PATH) ? fs.readFileSync(REPORT_PATH, 'utf8') : '';
    if (current !== report) {
      process.stderr.write('\nFLOW_LINT_REPORT.md is out of date. Run: node scripts/lint-flows.js --write\n');
      process.exit(1);
    }
    process.stdout.write('\nReport is up to date.\n');
    return;
  }

  if (write) {
    fs.writeFileSync(REPORT_PATH, report);
    process.stdout.write('\nWrote ' + path.relative(ROOT, REPORT_PATH).replace(/\\/g, '/') + '\n');
  }
}

main();
